KPL/MK

\begindata

  PATH_VALUES     = (
                      '/opt/isis3/data/osirisrex/apophis',
                      '/opt/isis3/data',
                      '/opt/isis3/data/osirisrex'
                    )

  PATH_SYMBOLS    = (
                      'apophis',
                      'data',
                      'osirisrex'
                    )

  KERNELS_TO_LOAD = (
                      '$osirisrex/kernels/lsk/naif0012.tls',
                      '$osirisrex/kernels/pck/bennu_v15.tpc',
                      '$osirisrex/kernels/sclk/ORX_SCLKSCET.00071.tsc',
                      '$osirisrex/kernels/fk/orx_v14.tf',
                      '$osirisrex/kernels/tspk/de424.bsp',
                      '$osirisrex/kernels/tspk/sb-101955-76.bsp',
                      '$osirisrex/kernels/tspk/bennu_refdrmc_v1.bsp',
                      '$osirisrex/kernels/pck/pck00010.tpc',
                      '$osirisrex/kernels/spk/orx_struct_v04.bsp'
                    )

\begintext
Metakernel file generated by PSMRTS: 
2026-03-20 12:03:30
Source: ../psmrts/core/tests/data/orx_kernels.mk
