# This workflow is intended to test PSMRTS builds on Linux and Mac platforms on any commits to the main branch.
# There is basic output for code coverage in the Linux build, but only reports an overall percentage -- 
# for more indepth coverage please follow the noted commands in that section of the workflow (creates an html 
# report that details per file / function).
name: CMake on Multiple Platforms

on:
  #push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: release 
  
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      
      matrix:
        os: [windows-latest, ubuntu-latest] #, macos-latest]
        build_type: [Release]
        include:
        # - os: macos-latest
         #  c_compiler: gcc
         #  cpp_compiler: g++
         - os: ubuntu-latest
           c_compiler: gcc
           cpp_compiler: g++
         - os: windows-latest
           c_compiler: MSVC
           cpp_compiler: MSVC
            
    steps:
    - name: Deleting Unnecessary Tool Cache Folder
      if: runner.os != 'Windows'
      run: rm -rf /opt/hostedtoolcache

    - name: Deleting Unnecessary Tool Cache Folder (Windows)
      if: runner.os == 'Windows'
      run: |
        if (Test-Path "C:\hostedtoolcache\windows") {
          Get-ChildItem -Path C:\hostedtoolcache\windows -Recurse | ForEach-Object {
            Write-Host "Deleting: $($_.FullName)"
            Remove-Item -Path $_.FullName -Recurse -Force
          }
        }
        else {
          Write-Output "Directory Not Found: C:\hostedtoolcache"
        }
      
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}


    - name: Ensure gcovr Dependency (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov gcovr
        

    - name: Build PSMRTS Environment (Linux)
      if: runner.os == 'Linux'
      run: |
       export PSMRTS_ROOT=${PWD}
       export VCPKG_ROOT=${PWD}/vcpkg
       git clone https://github.com/microsoft/vcpkg
       ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
       # ./scripts/install_vcpkg_packages.sh
       ./make_psmrts.sh -t -c -d -V 
       du -sh .

   # - name: Build PSMRTS Environment (Mac)
    #  if: runner.os == 'macOS'
    #  run: |
     #   export PSMRTS_ROOT=${PWD}
      #  export VCPKG_ROOT=${PWD}/vcpkg
      #  git clone https://github.com/microsoft/vcpkg
      #  ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
      #  ./scripts/install_vcpkg_packages.sh
       # ./scripts/build_psmrts.sh -t  -c -d
      #  du -sh .
      
    - name: Set up MSBuild
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.1

    - name: Build PSMRTS Environment (Windows)
      if: runner.os == 'Windows'
      run: |
        .\make_psmrts.ps1 -t -V -j 4
        Write-Host "Size in GB:"
        Get-ChildItem -Recurse | Measure-Object -Property Length -Sum | ForEach-Object {
          [math]::Round($_.Sum / 1GB, 2)
        }

    - name: Run Tests (Linux/Mac)
      if: runner.os != 'Windows'
      run: |
        cd build
        ctest --output-on-failure

    - name: Run Tests (Windows)
      if: runner.os == 'Windows'
      run: |
        Set-Location -Path ".\build"
        MSBuild psmrts.sln /p:Configuration=Release
        Get-Command ctest
        ctest -C Release --output-on-failure


    - name: Basic Coverage
      if: runner.os == 'Linux'
      run: |
        echo "For more detailed report, open resulting html file when in build directory by running the following commands: "
        echo "cmake --build build --target lcov_coverage"
        echo "open .build/lcov_coverage/index.html"
        #lcov --directory . --capture --output-file coverage.info
        #lcov --summary coverage.info
        cmake --build build --target lcov_coverage
